build: false

cache:
  #- packages

platform:
    -x64

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA% %PYTHON_ARCH%"

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  # - ps: $screen_resolution = '1280x800'; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  # ------------------- PYTHON ENVIRONNEMENT -------------------
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n testenv python=%PYTHON_VERSION% numpy scipy matplotlib pip cython"
  # Activate testing environnement :
  - "activate testenv"
  - "python -m pip install --upgrade pip"
  # Install dependencies :
  - "pip install pytest pandas statsmodels scikit-learn"
  - "dir"
  # ------------------- PINGOUIN -------------------
  - "python setup.py develop"

test_script:
  - "pytest"
